/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pencereler;

import Sınıflar.Kullanici;
import Sınıflar.Kullanicilar;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author emir
 */
public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form GirisEkrani
     */
    Kullanicilar kullanicilar;

    /*"GirisEkrani" sınıfının kurucu metodunda, başlangıç bileşenlerinin (UI bileşenleri) oluşturulması ve ayarlanması gerçekleştirilir.
    Ayrıca "Kullanicilar" sınıfından bir nesne oluşturulur.*/
    public GirisEkrani() {
        initComponents();
        kullanicilar = new Kullanicilar();
        ImageIcon image = new ImageIcon(getClass().getResource("logo.png"));
        lbl_logo.setIcon(image);
        ImageIcon image2 = new ImageIcon(getClass().getResource("icon60.png"));
        lbl_icon.setIcon(image2);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /*"kullaniciSil" metodu, bir kullanıcı nesnesinin silinmesini sağlar. Bu metod, "Kullanicilar" sınıfındaki "kullaniciSil" metodunu çağırır.*/
    public void kullaniciSil(Kullanici kullanici) {
        kullanicilar.kullaniciSil(kullanici);
    }

    /*"kullaniciEkle" metodu, bir kullanıcı nesnesinin eklenmesini sağlar. Bu metod, "Kullanicilar" sınıfındaki "kullaniciEkle" metodunu çağırır.*/
    public void kullaniciEkle(Kullanici kullanici) {
        kullanicilar.kullaniciEkle(kullanici);
    }

    /*"sifreDegistir" metodu, bir kullanıcının şifresini değiştirmeyi sağlar. Bu metod, kullanıcı adı, eski şifre ve yeni şifre parametrelerini alır. 
    "Kullanicilar" sınıfından kullanıcı listesini alır ve döngüyle bu listeyi kontrol eder. Eşleşen kullanıcıyı bulduğunda, şifresini yeni şifreyle değiştirir.*/
    public void sifreDegistir(String eskiSifre, String yeniSifre, String kullaniciAdi) {
        ArrayList<Kullanici> kullaniciListesi = kullanicilar.kullanicilariAl();
        for (Kullanici kullanici : kullaniciListesi) {
            if (kullanici.getKullaniciAdi().equals(kullaniciAdi) && kullanici.getSifre().equals(eskiSifre)) {
                kullanici.setSifre(yeniSifre);
            }
        }
    }

    /*"kullaniciAdiniDegistir" metodu, bir kullanıcının kullanıcı adını değiştirmeyi sağlar. Bu metod, eski kullanıcı adı, şifre ve yeni kullanıcı adı parametrelerini alır. 
    "Kullanicilar" sınıfından kullanıcı listesini alır ve döngüyle bu listeyi kontrol eder. Eşleşen kullanıcıyı bulduğunda, kullanıcı adını yeni kullanıcı adıyla değiştirir.*/
    public void kullaniciAdiniDegistir(String eskiAd, String sifre, String yeniAd) {
        ArrayList<Kullanici> kullaniciListesi = kullanicilar.kullanicilariAl();
        for (Kullanici kullanici : kullaniciListesi) {
            if (kullanici.getKullaniciAdi().equals(eskiAd) && kullanici.getSifre().equals(sifre)) {
                kullanici.setKullaniciAdi(yeniAd);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_giris = new javax.swing.JPanel();
        lbl_sifre = new javax.swing.JLabel();
        rbtn_kullanici = new javax.swing.JRadioButton();
        rbtn_yonetici = new javax.swing.JRadioButton();
        btn_kayit = new javax.swing.JButton();
        btn_giris = new javax.swing.JButton();
        lbl_kullaniciAdi = new javax.swing.JLabel();
        txt_kullaniciAdi = new javax.swing.JTextField();
        lbl_kayitSorusu = new javax.swing.JLabel();
        txt_sifre = new javax.swing.JPasswordField();
        lbl_kutuphanesi = new javax.swing.JLabel();
        lbl_dostlar = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_giris.setBackground(new java.awt.Color(255, 255, 255));
        pnl_giris.setMaximumSize(new java.awt.Dimension(404, 512));
        pnl_giris.setMinimumSize(new java.awt.Dimension(404, 512));
        pnl_giris.setPreferredSize(new java.awt.Dimension(404, 512));
        pnl_giris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sifre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_sifre.setForeground(new java.awt.Color(51, 102, 255));
        lbl_sifre.setText("Şifre");
        pnl_giris.add(lbl_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, 40));

        buttonGroup1.add(rbtn_kullanici);
        rbtn_kullanici.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn_kullanici.setForeground(new java.awt.Color(51, 102, 255));
        rbtn_kullanici.setSelected(true);
        rbtn_kullanici.setText("Kullanıcı");
        pnl_giris.add(rbtn_kullanici, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 90, 30));

        buttonGroup1.add(rbtn_yonetici);
        rbtn_yonetici.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn_yonetici.setForeground(new java.awt.Color(51, 102, 255));
        rbtn_yonetici.setText("Yönetici");
        pnl_giris.add(rbtn_yonetici, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 110, 30));

        btn_kayit.setBackground(new java.awt.Color(51, 102, 255));
        btn_kayit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_kayit.setForeground(new java.awt.Color(255, 255, 255));
        btn_kayit.setText("Kayıt Ol");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });
        pnl_giris.add(btn_kayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 80, 20));

        btn_giris.setBackground(new java.awt.Color(51, 102, 255));
        btn_giris.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_giris.setForeground(new java.awt.Color(255, 255, 255));
        btn_giris.setText("Giriş Yap");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });
        pnl_giris.add(btn_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 240, -1));

        lbl_kullaniciAdi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_kullaniciAdi.setForeground(new java.awt.Color(51, 102, 255));
        lbl_kullaniciAdi.setText("Kullanıcı Adı");
        pnl_giris.add(lbl_kullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 140, 30));
        pnl_giris.add(txt_kullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 240, -1));

        lbl_kayitSorusu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_kayitSorusu.setText("Bir hesabınız yok mu?");
        pnl_giris.add(lbl_kayitSorusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 150, 20));
        pnl_giris.add(txt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 240, -1));

        lbl_kutuphanesi.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        lbl_kutuphanesi.setForeground(new java.awt.Color(51, 102, 255));
        lbl_kutuphanesi.setText("KÜTÜPHANESI|");
        pnl_giris.add(lbl_kutuphanesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, -1));

        lbl_dostlar.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        lbl_dostlar.setForeground(new java.awt.Color(51, 102, 255));
        lbl_dostlar.setText("| DOSTLAR");
        pnl_giris.add(lbl_dostlar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 30));
        pnl_giris.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 50));
        pnl_giris.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 70, 70));

        getContentPane().add(pnl_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 489));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed
        /*Bu kod satırları, mevcut pencereden "KayitEkrani" adlı bir kayıt ekranına geçiş yapmayı sağlar. Önce mevcut pencere kapatılır ve ardından yeni kayıt ekranı görüntülenir.*/
        KayitEkrani kayit = new KayitEkrani();
        this.dispose();
        kayit.show();
    }//GEN-LAST:event_btn_kayitActionPerformed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed

        String kullaniciAdi = txt_kullaniciAdi.getText();
        String sifre = txt_sifre.getText();

        /*Kullanıcı adının boş olup olmadığını kontrol eder. Eğer boşsa, kullanıcıya bir uyarı mesajı gösterir ve işlemi sonlandırır.*/
        if (kullaniciAdi.compareTo("") == 0) {
            JOptionPane.showMessageDialog(rootPane, "Kullanıcı adınızı girmelisiniz!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }
        /*Şifrenin boş olup olmadığını kontrol eder. Eğer boşsa, kullanıcıya bir uyarı mesajı gösterir ve işlemi sonlandırır.*/ 
        else if (sifre.compareTo("") == 0) {
            JOptionPane.showMessageDialog(rootPane, "Şifrenizi girmelisiniz!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        /*Eğer "yonetici" radyo düğmesi seçili ise, kullanıcı adı ve şifrenin "admin" olarak girilip girilmediğini kontrol eder. 
        Eğer doğru ise, bir "YoneticiEkrani" nesnesi oluşturur, yönetici bilgilerini ayarlar, mevcut pencereyi kapatır ve yönetici ekranını gösterir.
        Eğer kullanıcı adı veya şifre yanlış ise, kullanıcıya bir uyarı mesajı gösterir.*/
        if (rbtn_yonetici.isSelected()) {

            if (kullaniciAdi.equals("admin") && sifre.equals("admin")) {
                YoneticiEkrani yonetici = new YoneticiEkrani();
                yonetici.setYoneticiBilgileri("Utku", "utku_dostlar_kutuphanesi@hotmail.com");
                this.dispose();
                yonetici.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Yanlış kullanıcı adı veya şifre girişi yaptınız.\nLütfen tekrar deneyiniz.", "Uyarı", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            /*Eğer "yonetici" radyo düğmesi seçili değil ise, "kullanicilar" adlı bir nesnenin "isUserInformationTrue" ve "bilgiAlma" metodlarıyla kullanıcı adı ve şifrenin doğruluğunu kontrol eder. 
            Eğer doğru ise, "KullaniciEkrani" nesnesi oluşturur, kullanıcı bilgilerini ayarlar, mevcut pencereyi kapatır ve kullanıcı ekranını gösterir.
            Eğer kullanıcı adı veya şifre yanlış ise, kullanıcıya bir uyarı mesajı gösterir.*/
            boolean kontrol = kullanicilar.kullaniciBilgileriDogrumu(kullaniciAdi, sifre);
            if (kontrol == false) {
                JOptionPane.showMessageDialog(rootPane, "Yanlış kullanıcı adı veya şifre girişi yaptınız.\nLütfen tekrar deneyiniz.", "Uyarı", JOptionPane.WARNING_MESSAGE);
            } else {
                /*Bu kod parçacığı, kullanıcı adı ve şifre doğrulama işlemlerini gerçekleştirerek, kullanıcıya uygun bir ekranı göstermeyi sağlar.*/
                Kullanici özelKullanici = kullanicilar.bilgiAlma(kullaniciAdi);
                KullaniciEkrani kullanici = new KullaniciEkrani();
                kullanici.setKullaniciBilgileri(özelKullanici.getKullaniciAdi(), özelKullanici.getAdres());
                this.dispose();
                kullanici.show();

            }
        }
    }//GEN-LAST:event_btn_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris;
    private javax.swing.JButton btn_kayit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbl_dostlar;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_kayitSorusu;
    private javax.swing.JLabel lbl_kullaniciAdi;
    private javax.swing.JLabel lbl_kutuphanesi;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JPanel pnl_giris;
    private javax.swing.JRadioButton rbtn_kullanici;
    private javax.swing.JRadioButton rbtn_yonetici;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
