/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pencereler;

import Sınıflar.Kullanicilar;
import Sınıflar.Regex;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author emir
 */
public class KullaniciAdiDegistirmeEkrani extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciAdiDegistirmeEkrani
     */
    Kullanicilar kullaniciListesi;
    Regex regex;
    GirisEkrani giris;

    public KullaniciAdiDegistirmeEkrani() {
        initComponents();
        /*İlk olarak, Kullanicilar sınıfından bir kullaniciListesi nesnesi oluşturulur. Bu nesne, kullanıcılarla ilgili işlemleri gerçekleştirmek için kullanılacaktır.*/
        /*GirisEkrani sınıfından bir giris nesnesi oluşturulur. Bu nesne, kullanıcının kullanıcı adını değiştirdikten sonra giriş ekranına dönebilmesi için kullanılacaktır.*/
        /*Ardından, Regex sınıfından bir regex nesnesi oluşturulur. Bu nesne, kullanıcı adı doğrulama işlemlerinde kullanılacaktır.*/
        kullaniciListesi = new Kullanicilar();
        regex = new Regex();
        giris = new GirisEkrani();
        ImageIcon image = new ImageIcon(getClass().getResource("logo.png"));
        lbl_logo.setIcon(image);
        ImageIcon image2 = new ImageIcon(getClass().getResource("icon60.png"));
        lbl_icon.setIcon(image2);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_kullaniciAdiDegistirme = new javax.swing.JPanel();
        lbl_yeniKullaniciAdiTekrar = new javax.swing.JLabel();
        btn_kullaniciAdiniDegistir = new javax.swing.JButton();
        lbl_kullaniciAdi = new javax.swing.JLabel();
        txt_yeniKullaniciAdiTekrar = new javax.swing.JTextField();
        lbl_sifre = new javax.swing.JLabel();
        txt_sifre = new javax.swing.JPasswordField();
        lbl_yeniKullaniciAdi = new javax.swing.JLabel();
        txt_eskiKullaniciAdi = new javax.swing.JTextField();
        txt_yeniKullaniciAdi = new javax.swing.JTextField();
        lbl_logo = new javax.swing.JLabel();
        lbl_kutuphanesi = new javax.swing.JLabel();
        lbl_dostlar = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_kullaniciAdiDegistirme.setBackground(new java.awt.Color(255, 255, 255));
        pnl_kullaniciAdiDegistirme.setMaximumSize(new java.awt.Dimension(404, 512));
        pnl_kullaniciAdiDegistirme.setMinimumSize(new java.awt.Dimension(404, 512));
        pnl_kullaniciAdiDegistirme.setPreferredSize(new java.awt.Dimension(404, 512));
        pnl_kullaniciAdiDegistirme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_yeniKullaniciAdiTekrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_yeniKullaniciAdiTekrar.setForeground(new java.awt.Color(51, 102, 255));
        lbl_yeniKullaniciAdiTekrar.setText("Yeni Kullanıcı Adı Tekrar");
        pnl_kullaniciAdiDegistirme.add(lbl_yeniKullaniciAdiTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 190, -1));

        btn_kullaniciAdiniDegistir.setBackground(new java.awt.Color(51, 102, 255));
        btn_kullaniciAdiniDegistir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_kullaniciAdiniDegistir.setForeground(new java.awt.Color(255, 255, 255));
        btn_kullaniciAdiniDegistir.setText("Kullanıcı Adını Değiştir");
        btn_kullaniciAdiniDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kullaniciAdiniDegistirActionPerformed(evt);
            }
        });
        pnl_kullaniciAdiDegistirme.add(btn_kullaniciAdiniDegistir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 240, -1));

        lbl_kullaniciAdi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_kullaniciAdi.setForeground(new java.awt.Color(51, 102, 255));
        lbl_kullaniciAdi.setText("Kullanıcı Adı");
        pnl_kullaniciAdiDegistirme.add(lbl_kullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 30));
        pnl_kullaniciAdiDegistirme.add(txt_yeniKullaniciAdiTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 240, -1));

        lbl_sifre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_sifre.setForeground(new java.awt.Color(51, 102, 255));
        lbl_sifre.setText("Şifre");
        pnl_kullaniciAdiDegistirme.add(lbl_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, -1));
        pnl_kullaniciAdiDegistirme.add(txt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 240, -1));

        lbl_yeniKullaniciAdi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_yeniKullaniciAdi.setForeground(new java.awt.Color(51, 102, 255));
        lbl_yeniKullaniciAdi.setText("Yeni Kullanıcı Adı");
        pnl_kullaniciAdiDegistirme.add(lbl_yeniKullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 140, -1));
        pnl_kullaniciAdiDegistirme.add(txt_eskiKullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 240, -1));
        pnl_kullaniciAdiDegistirme.add(txt_yeniKullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 240, -1));
        pnl_kullaniciAdiDegistirme.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 60));

        lbl_kutuphanesi.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        lbl_kutuphanesi.setForeground(new java.awt.Color(51, 102, 255));
        lbl_kutuphanesi.setText("KÜTÜPHANESI|");
        pnl_kullaniciAdiDegistirme.add(lbl_kutuphanesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, -1));

        lbl_dostlar.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        lbl_dostlar.setForeground(new java.awt.Color(51, 102, 255));
        lbl_dostlar.setText("| DOSTLAR");
        pnl_kullaniciAdiDegistirme.add(lbl_dostlar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 30));
        pnl_kullaniciAdiDegistirme.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 70, 70));

        getContentPane().add(pnl_kullaniciAdiDegistirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 502));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kullaniciAdiniDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kullaniciAdiniDegistirActionPerformed

        /*İlk olarak, kullanıcıdan mevcut kullanıcı adı, şifre, yeni kullanıcı adı ve yeni kullanıcı adını tekrar girmesi istenir ve bu değerler ilgili değişkenlere atanır.
        Ardından, boş bir kullanıcı adı girilip girilmediği kontrol edilir. Eğer boş bir kullanıcı adı girilmişse uyarı mesajı gösterilir.*/
        String eskiAd = txt_eskiKullaniciAdi.getText();
        String sifre = txt_sifre.getText();
        String yeniAd = txt_yeniKullaniciAdi.getText();
        String yeniAdTekrar = txt_yeniKullaniciAdiTekrar.getText();
        if (eskiAd.compareTo("") == 0) {
            JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı boş bırakılamaz!", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } else if (sifre.compareTo("") == 0) {
            /*Şifrenin boş olup olmadığı kontrol edilir. Eğer boş bir şifre girilmişse uyarı mesajı gösterilir.*/
            JOptionPane.showMessageDialog(rootPane, "Şifrenizi girmelisiniz!!", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } else if (yeniAd.compareTo("") == 0) {
            /*Yeni kullanıcı adının boş olup olmadığı kontrol edilir. Eğer boş bir yeni kullanıcı adı girilmişse uyarı mesajı gösterilir.*/
            JOptionPane.showMessageDialog(rootPane, "Yeni kullanıcı adınızı girmelisiniz!", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } else if (yeniAdTekrar.compareTo("") == 0) {
            JOptionPane.showMessageDialog(rootPane, "Yeni kullanıcı adınızı tekrar girmelisiniz!", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } else if (!yeniAd.equals(yeniAdTekrar)) {
            /*Yeni kullanıcı adının tekrar girilen yeni kullanıcı adıyla aynı olup olmadığı kontrol edilir. Eğer farklı ise uyarı mesajı gösterilir.*/

            JOptionPane.showMessageDialog(rootPane, "Girdiğiniz yeni kullanıcı adları aynı olmalıdır!", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } else if (kullaniciListesi.kullaniciAdiAlinmismi(yeniAd)) {
            /*Yeni kullanıcı adının kullanıcı listesinde zaten alınmış bir kullanıcı adı olup olmadığı kontrol edilir. Eğer kullanıcı adı alınmışsa uyarı mesajı gösterilir.*/
            JOptionPane.showMessageDialog(rootPane, "Bu kullanıcı adı zaten oluşturuldu.\nLütfen başka bir kullanıcı adı deneyin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } else if (kullaniciListesi.kullaniciBilgileriDogrumu(eskiAd, sifre)) {
            /*Mevcut kullanıcı adı ve şifrenin doğru olup olmadığı kontrol edilir. Eğer doğru ise, yeni kullanıcı adının belirli kurallara uygun olup olmadığı kontrol edilir. 
            Eğer kurallara uygunsa kullanıcı adı değiştirilir, başarılı bir mesaj gösterilir ve giriş ekranına yönlendirilir.*/
            if (regex.regexForUsername(yeniAd)) {
                kullaniciListesi.kullaniciAdiniDegistir(eskiAd, sifre, yeniAd);
                JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı başarıyla değiştirildi.\nLütfen yeni bilgilerinizle giriş yapın.", "", JOptionPane.INFORMATION_MESSAGE);
                giris.kullaniciAdiniDegistir(eskiAd, sifre, yeniAd);
                this.dispose();
                giris.show();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı geçerli değil! Lütfen kullanıcı adı kurallarına dikkat edin! ;\n"
                        + "En az 7 karakter ve harf, sayı ve '_' '/' karakterleri içerebilir. Ayrıca harflerle başlamalıdır.\n"
                        + "Örnek bir geçerli kullanıcı adı: utkubaran.124",
                        "Uyarı", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Girdiğiniz kullanıcı bilgileri doğru değil.\nLütfen tekrar deneyin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_kullaniciAdiniDegistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdiDegistirmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdiDegistirmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdiDegistirmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciAdiDegistirmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciAdiDegistirmeEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kullaniciAdiniDegistir;
    private javax.swing.JLabel lbl_dostlar;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_kullaniciAdi;
    private javax.swing.JLabel lbl_kutuphanesi;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JLabel lbl_yeniKullaniciAdi;
    private javax.swing.JLabel lbl_yeniKullaniciAdiTekrar;
    private javax.swing.JPanel pnl_kullaniciAdiDegistirme;
    private javax.swing.JTextField txt_eskiKullaniciAdi;
    private javax.swing.JPasswordField txt_sifre;
    private javax.swing.JTextField txt_yeniKullaniciAdi;
    private javax.swing.JTextField txt_yeniKullaniciAdiTekrar;
    // End of variables declaration//GEN-END:variables
}
